// Code generated by "stringer -type=BomTool"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Syft-0]
	_ = x[K8Bom-1]
	_ = x[SpdxBom-2]
	_ = x[MsBom-3]
}

const _BomTool_name = "SyftK8BomSpdxBomMsBom"

var _BomTool_index = [...]uint8{0, 4, 9, 16, 21}

func (i BomTool) String() string {
	if i < 0 || i >= BomTool(len(_BomTool_index)-1) {
		return "BomTool(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _BomTool_name[_BomTool_index[i]:_BomTool_index[i+1]]
}
